AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
]

App/models.py
from django.db import models


class Main(models.Model):

    img = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    trackid = models.IntegerField(default=1)

    class Meta:
        abstract = True


class MainWheel(Main):

    """
    insert into axf_wheel(img,name,trackid) values("http://img01.bqstatic.com//upload/activity/2017031716035274.jpg@90Q.jpg",
    "酸奶女王","21870"),("http://img01.bqstatic.com//upload/activity/2017031710450787.jpg@90Q.jpg","优选圣女果","21869"),
    ("http://img01.bqstatic.com//upload/activity/2017030714522982.jpg@90Q.jpg","伊利酸奶大放价","21862"),
    ("http://img01.bqstatic.com//upload/activity/2017032116081698.jpg@90Q.jpg","鲜货直供－窝夫小子","21770"),
    ("http://img01.bqstatic.com//upload/activity/2017032117283348.jpg@90Q.jpg","鲜货直供－狼博森食品","21874");
    """
    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):
    """
    insert into axf_nav(img,name,trackid) values("http://img01.bqstatic.com//upload/activity/2017032016495169.png",
    "每日必抢","21851"),("http://img01.bqstatic.com//upload/activity/2016121920130294.png","每日签到","21753"),
    ("http://img01.bqstatic.com//upload/activity/2017010517013925.png","鲜货直供","21749"),
    ("http://img01.bqstatic.com//upload/activity/2017031518404137.png","鲜蜂力荐","21854");

    """
    class Meta:
        db_table = "axf_nav"


class MustBuy(Main):

    """
    insert into axf_mustbuy(img,name,trackid) values("http://img01.bqstatic.com//upload/activity/2017031715194326.
    jpg@90Q.jpg","酸奶女王","21870"),("http://img01.bqstatic.com//upload/activity/cms_118826_1489742316.jpg@90Q",
    "鲜果女王","21861"),("http://img01.bqstatic.com//upload/activity/2017031011044918.jpg@90Q.jpg","麻辣女王","21866"),
    ("http://img01.bqstatic.com//upload/activity/2017022318314545.jpg@90Q.jpg","鲜货直供－果析","21858");

    """

    class Meta:
        db_table = "axf_mustbuy"

App/views.py
from django.http import HttpResponse
from django.shortcuts import render

from App.models import MainWheel, MainNav, MustBuy


def index(request):
    return HttpResponse('index')


def home(request):

    main_wheels = MainWheel.objects.all()

    main_navs = MainNav.objects.all()

    must_buys = MustBuy.objects.all()

    data = {
        "main_wheels": main_wheels,
        "main_navs": main_navs,
        "must_buys": must_buys,
    }

    return render(request, 'main/home.html', context=data)


def market(request):

    return render(request, 'main/market.html')


def cart(request):

    return render(request, 'main/cart.html')


def mine(request):
    return render(request, 'main/mine.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    {% block ext_css %}

    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    {% block ext_js %}

    {% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block footer %}

    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
            <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>
            <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
            <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>


{% endblock %}

templates/main/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/cart.css' %}">
{% endblock %}

templates/main/home.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/main/js/home.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="home">
        {#  首页轮播  #}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide"><img src="{% static 'img/home/slide1.jpg' %}" alt=""></div>
                <div class="swiper-slide"><img src="{% static 'img/home/slide2.jpg' %}" alt=""></div>
                <div class="swiper-slide"><img src="{% static 'img/home/slide3.jpg' %}" alt=""></div>
                <div class="swiper-slide"><img src="{% static 'img/home/slide4.jpg' %}" alt=""></div>
            </div>
            <div class="swiper-pagination"></div>
        </div>


        {# 顶部菜单 #}
        <div class="topMenu">
            <nav>
                <ul>
                    {% for main_nav in main_navs %}
                        <li>
                            <img src="{{ main_nav.img }}" alt="">
                            <span>{{ main_nav.name }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>


        {#  中间轮播  #}
        <div class="swiper-container" id="swiperMenu">
            <ul class="swiper-wrapper">
                <li class="swiper-slide"><img src="{% static 'img/home/slide1.jpg' %}" alt=""></li>
                <li class="swiper-slide"><img src="{% static 'img/home/slide2.jpg' %}" alt=""></li>
                <li class="swiper-slide"><img src="{% static 'img/home/slide3.jpg' %}" alt=""></li>
                <li class="swiper-slide"><img src="{% static 'img/home/slide4.jpg' %}" alt=""></li>
            </ul>
        </div>


    </div>

{% endblock %}

templates/main/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/market.css' %}">
{% endblock %}

templates/main/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/mine.css' %}">
{% endblock %}